language: python
python:
  - "3.8"

dist: "trusty"

cache: 
  - pip

install:
  - sudo apt-get update -y
  - python3 -m venv $HOME/$TRAVIS_PROJECTRECIPE_ENV/env
  - source $HOME/$TRAVIS_PROJECTRECIPE_ENV/env/bin/activate
  - pip3 install --user --upgrade pip
  - pip3 install --user -r requirements.txt


deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: projectrecipe-travis-latest-2020
    skip_cleanup: true
    acl: private

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: projectrecipe-travis-latest-2020
    key: releases/projectrecipe.zip
    bundle_type: zip
    application: projectrecipe
    deployment_group: projectrecipe-dev-deployment-group
    region: us-east-1
    on:
      branch: master

script:
  - echo $TRAVIS_PYTHON_VERSION
  - echo $TRAVIS_PROJECTRECIPE_ENV
  - echo $TRAVIS_BUILD_DIR
  - source $HOME/$TRAVIS_PROJECTRECIPE_ENV/env/bin/activate
  - python --version
  - pip3 --version
  - pytest projectrecipe/*.py
  - zip -r projectrecipe *
  - mkdir -p releases
  - mv projectrecipe.zip releases/projectrecipe.zip
  - ls -l 