language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

install:
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -n base -c defaults conda
  - conda info -a # Useful for debugging any issues with conda

  - conda create --name $TRAVIS_PROJECTRECIPE_ENV python=$TRAVIS_PYTHON_VERSION
  - conda activate $TRAVIS_PROJECTRECIPE_ENV
  - conda install --file requirements.txt

script:
  - echo $TRAVIS_PYTHON_VERSION
  - echo $TRAVIS_PROJECTRECIPE_ENV
  - pytest projectrecipe/*.py